src/Entity/Charity.php
<?php

namespace App\Entity;

use App\Repository\CharityRepository;
use DateTime;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\BlobType;
use Doctrine\ORM\Mapping as ORM;
use PhpParser\Node\Expr\Cast\Double;
use PhpParser\Node\Expr\Cast\String_;
use Symfony\Component\Validator\Constraints\Date;


#[ORM\Entity(repositoryClass: CharityRepository::class)]
class Charity
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;




    #[ORM\Column(length: 255)]
    private ?string $name_of_charity;

    #[ORM\Column]
    private ?float $amount_donated;

    #[ORM\Column]
    private ?float $total_of_donation;

    #[ORM\Column]
    private ?DateTime $last_date;



    #[ORM\Column(length: 255)]
    private ?string $picture = null;

    #[ORM\ManyToMany(targetEntity: Donation::class, inversedBy: 'charities')]
    private Collection $donation;

    #[ORM\Column(length: 255)]
    private ?string $location = null;

    #[ORM\Column(length: 255)]
    private ?string $search_keyword = null;

    public function __construct()
    {
        $this->donation = new ArrayCollection();
    }


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getAmountDonated(): ?float
    {
        return $this->amount_donated;
    }

    public function setAmountDonated(float $amount_donated): static
    {
        $this->amount_donated = $amount_donated;
        return $this;
    }

    public function getTotalOfDonation(): ?float
    {
        return $this->total_of_donation;
    }

    public function setTotalOfDonation(float $total_of_donation): static
    {
        $this->total_of_donation = $total_of_donation;
        return $this;
    }

    public function getLastDate(): ?DateTime
    {
        return $this->last_date;
    }

    public function setLastDate(DateTime $last_date): static
    {
        $this->last_date = $last_date;
        return $this;
    }

    public function getNameOfCharity(): ?string
    {
        return $this->name_of_charity;
    }

    public function setNameOfCharity(string $name_of_charity): static
    {
        $this->name_of_charity = $name_of_charity;
        return $this;
    }

    public function getPicture(): ?string
    {
        return $this->picture;
    }

    public function setPicture(string $picture): static
    {
        $this->picture = $picture;
        return $this;
    }
    public function __toString()
    {
        return $this->name_of_charity;
    }

    /**
     * @return Collection<int, Donation>
     */
    public function getDonation(): Collection
    {
        return $this->donation;
    }

    public function addDonation(Donation $donation): static
    {
        if (!$this->donation->contains($donation)) {
            $this->donation->add($donation);
        }

        return $this;
    }

    public function removeDonation(Donation $donation): static
    {
        $this->donation->removeElement($donation);

        return $this;
    }

    public function getLocation(): ?string
    {
        return $this->location;
    }

    public function setLocation(string $location): static
    {
        $this->location = $location;

        return $this;
    }

    public function getSearchKeyword(): ?string
    {
        return $this->search_keyword;
    }

    public function setSearchKeyword(string $search_keyword): static
    {
        $this->search_keyword = $search_keyword;

        return $this;
    }
}

src/Controller/CharityFrontController.php
<?php

namespace App\Controller;

use App\Entity\Charity;
use App\Form\Charity1Type;
use App\Repository\CharityRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/charity/front')]
class CharityFrontController extends AbstractController
{
    #[Route('/all', name: 'app_charity_front_index', methods: ['GET'])]
    public function index(CharityRepository $charityRepository): Response
    {
        $user = $this->getUser();
        return $this->render('charity_front/index.html.twig', [
            'charities' => $charityRepository->findAll(),
            'user' => $user,
        ]);
    }

    #[Route('/new', name: 'app_charity_front_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $charity = new Charity();
        $form = $this->createForm(CharityType::class, $charity);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            // Récupérer le fichier téléchargé depuis le formulaire
            $file = $form->get('picture')->getData();

            //handle photos upload second fucntion 
            $file = $form->get('picture')->getData(); // Get the uploaded file from the form
            if ($file) {
                //Handle photos upload
                $filename = md5(uniqid()) . '.' . $file->guessExtension();


                $file->move($this->getParameter('uploads_directory'), $filename);
                $charity->setPicture($filename);
            }




            // Persistez et flushz l'entité charity
            $entityManager->persist($charity);
            $entityManager->flush();

            // Rediriger vers la page d'index des charity
            return $this->redirectToRoute('app_charity_index', [], Response::HTTP_SEE_OTHER);
        }

        // Afficher le formulaire
        return $this->renderForm('charity/new.html.twig', [
            'charity' => $charity,
            'form' => $form,
        ]);
    }


    #[Route('/{id}', name: 'app_charity_front_show', methods: ['GET'])]
    public function show(Request $request, EntityManagerInterface $entityManager, Charity $charities): Response
    {


        return $this->render('charity_front/show.html.twig', [
            'charity' => $charities,
        ]);
    }

    /* #[Route('/{id}/edit', name: 'app_charity_front_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Charity $charity, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(Charity1Type::class, $charity);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_charity_front_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('charity_front/edit.html.twig', [
            'charity' => $charity,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_charity_front_delete', methods: ['POST'])]
    public function delete(Request $request, Charity $charity, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete' . $charity->getId(), $request->request->get('_token'))) {
            $entityManager->remove($charity);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_charity_front_index', [], Response::HTTP_SEE_OTHER);
    }*/
}

templates/charity_front/_delete_form.html.twig
<form method="post" action="{{ path('app_charity_front_delete', {'id': charity.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ charity.id) }}">
    <button class="btn">Delete</button>
</form>

templates/charity_front/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/charity_front/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Charity{% endblock %}

{% block body %}
    <h1>Edit Charity</h1>

    {{ include('charity_front/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_charity_front_index') }}">back to list</a>

    {{ include('charity_front/_delete_form.html.twig') }}
{% endblock %}

templates/charity_front/index.html.twig
{% extends 'home.html.twig' %}
{% block body %}

	<!-- Service Start -->
	<div class="container-xxl py-5">
		<div class="container">
			<div class="text-center mx-auto wow fadeInUp" data-wow-delay="0.1s" style="max-width: 500px;">
				<p class="fs-5 fw-bold text-primary">Our Charities</p>
				<hr>
				<hr>
				<h1 class="display-5 mb-5">Charities That We Offer For You</h1>
			</div>
			<div class="row g-4">
				{% for charity in charities %}
					<div class="col-lg-4 col-md-6 wow fadeInUp" data-wow-delay="0.{{ loop.index }}">
						<div class="service-item rounded d-flex h-100">
							<div class="service-img rounded">

								{% dump(charity.picture) %}


								<img src="{{ asset('uploads/' ~ charity.picture) }}" style="width: 100%; height: 100%;" alt="charity pic" class="img-fluid">
							</div>
							<div class="service-text rounded p-5">

								<h4 class="mb-3">{{ charity.nameOfCharity }}</h4>
								<p class="mb-4">Amount needed:
									{{ charity.amountDonated }}</p>

								<p class="mb-4">Last date of donation:
									{{ charity.lastDate|date('Y-m-d') }}</p>
								<a class="btn btn-sm" href="{{ path('app_charity_front_show', {id: charity.id})}}">
									<i class="fa fa-plus text-primary me-2"></i>show more</a>
							</div>
						</div>
					</div>
				{% endfor %}
			</div>
		</div>
	</div>
	<!-- Service End -->
{% endblock %}

templates/charity_front/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Charity
{% endblock %}

{% block body %}
	<h1>Create new Charity</h1>

	{{ include('charity_front/_form.html.twig') }}

	<a href="{{ path('app_charity_front_index') }}">back to list</a>
{% endblock %}

templates/charity_front/show.html.twig
{% extends 'baseFront.html.twig' %}
{% block body %}
	<!-- About Start -->
	<div class="container-xxl py-5">
		<div class="container">
			<div class="row g-5 align-items-end">
				<div class="col-lg-3 col-md-5 wow fadeInUp" data-wow-delay="0.1s">


					<img class="img-fluid rounded" data-wow-delay="0.1s" src="{{ asset('uploads/' ~ charity.picture) }}">
				</div>


				<div class="col-lg-6 col-md-7 wow fadeInUp" data-wow-delay="0.3s">
					<h1 class="display-1 text-primary mb-0">{{ charity.amountDonated }}</h1>
					<p class="text-primary mb-4">Dinars Tunisien</p>
					<h1 class="display-5 mb-4">{{ charity.nameOfCharity }}</h1>

					<a class="btn btn-primary py-3 px-4" href="{{ path('app_donation_new')}}">Donate</a>
				</div>


			</div>
		</div>
	</div>
	<!-- About End -->

{% endblock %}